

jobs:
  include:
    - stage: test
      language: node_js
      cache: npm
      node_js:
        - 10
      install:
        - npm i -g lerna
        - lerna bootstrap
      matrix:
        include:
          - name: wejay/spotify
            env: PACKAGE_LOCATION=packages/spotify
          - name: wejay/spotify-search
            env: PACKAGE_LOCATION=packages/spotify-search
          - name: wejay/spotify-track
            env: PACKAGE_LOCATION=packages/spotify-track
          - name: wejay/spotify-utils
            env: PACKAGE_LOCATION=packages/spotify-utils
      script:
        - cd $PACKAGE_LOCATION
        - npm test
        
    - stage: deploy
      if: branch = master
      after_success:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote add pub https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git -f
        - git checkout master

      deploy:
        - provider: script
          script: npx lerna publish --git-remote pub --yes
          skip_cleanup: true
          keep_history: true
          on:
      branch: master
stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request
