language: node_js

cache:
  directories:
    - '~/.npm'

node_js:
  - 10

install:
  - npm i -g lerna
  - lerna bootstrap

matrix:
  include:
    - name: wejay/spotify
      env: PACKAGE_LOCATION=packages/spotify
    - name: wejay/spotify-search
      env: PACKAGE_LOCATION=packages/spotify-search
    - name: wejay/spotify-track
      env: PACKAGE_LOCATION=packages/spotify-track
    - name: wejay/spotify-utils
      env: PACKAGE_LOCATION=packages/spotify-utils

script:
  - cd $PACKAGE_LOCATION
  - npm test
